# @format

name: List items

on:
    push:
        branches: [serve]

jobs:
    list_items:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: |
                  npm run json

                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  git add -A
                  git commit -m "List items"
                  git push
