# @format

name: Generate index.json and Readme.md

on:
    push:
        branches: [serve]

jobs:
    generate_files:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  npm run list
                  git add index.json
                  git commit -m "Generate index.json 🤖"

                  npm run readme
                  git add Readme.md
                  git commit -m "Generate Readme.md 🤖"

                  git push
